-- ISA Spectrum: real campus-wall zones, public safe feed, and daily meal ratings.
-- Idempotent: safe to run again after a partial setup.

begin;

-- 1. Store campus-wall zones as a real database field.
alter table public.messages
  add column if not exists zone text;

update public.messages
set zone = case
  when content ~ '^【校园生活】' then '校园生活'
  when content ~ '^【学习互助】' then '学习互助'
  when content ~ '^【活动社团】' then '活动社团'
  when content ~ '^【失物招领】' then '失物招领'
  when content ~ '(失物|招领|丢了|捡到|寻找|遗失|找到)' then '失物招领'
  when content ~ '(学习|作业|考试|课程|笔记|竞赛|选课|大学)' then '学习互助'
  when content ~ '(活动|社团|比赛|演出|运动|招新|音乐|篮球|足球)' then '活动社团'
  else '校园生活'
end
where zone is null
   or zone not in ('校园生活', '学习互助', '活动社团', '失物招领');

-- Remove the old visible marker after its value has been migrated.
update public.messages
set content = regexp_replace(content, '^【(校园生活|学习互助|活动社团|失物招领)】\s*', '')
where content ~ '^【(校园生活|学习互助|活动社团|失物招领)】';

alter table public.messages
  alter column zone set default '校园生活',
  alter column zone set not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.messages'::regclass
      and conname = 'messages_zone_check'
  ) then
    alter table public.messages
      add constraint messages_zone_check
      check (zone in ('校园生活', '学习互助', '活动社团', '失物招领'));
  end if;
end $$;

create index if not exists messages_zone_flag_created_at_idx
  on public.messages (zone, flag, created_at desc)
  where reply_to is null;

-- Recreate instead of CREATE OR REPLACE because the legacy view may contain
-- user_id/contact fields; PostgreSQL cannot remove view columns in place.
drop view if exists public.approved_messages_public;
create view public.approved_messages_public
with (security_barrier = true)
as
select id, username, content, zone, pic_url, created_at, reply_to
from public.messages
where flag = 1 and reply_to is null;

revoke all on table public.approved_messages_public from public;
grant select on table public.approved_messages_public to anon, authenticated;

-- Browser roles read only the safe projection, never the messages base table.
revoke all on table public.messages from anon, authenticated;

-- 2. Open daily meal feedback for signed-in users.
create table if not exists public.meal_ratings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 80),
  rating_date date not null,
  breakfast_score smallint not null check (breakfast_score between 1 and 5),
  lunch_score smallint not null check (lunch_score between 1 and 5),
  dinner_score smallint not null check (dinner_score between 1 and 5),
  comment text check (comment is null or char_length(comment) <= 500),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, rating_date)
);

alter table public.meal_ratings enable row level security;
revoke all on table public.meal_ratings from anon;
grant select, insert, update on table public.meal_ratings to authenticated;
grant usage, select on sequence public.meal_ratings_id_seq to authenticated;

drop policy if exists "Users can read their own meal ratings" on public.meal_ratings;
create policy "Users can read their own meal ratings"
on public.meal_ratings for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert their own meal ratings" on public.meal_ratings;
create policy "Users can insert their own meal ratings"
on public.meal_ratings for insert to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own meal ratings" on public.meal_ratings;
create policy "Users can update their own meal ratings"
on public.meal_ratings for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create or replace function public.set_meal_rating_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists meal_ratings_set_updated_at on public.meal_ratings;
create trigger meal_ratings_set_updated_at
before update on public.meal_ratings
for each row execute function public.set_meal_rating_updated_at();

commit;

select
  (select count(*) from public.messages where zone is not null) as zoned_messages,
  (select count(*) from public.meal_ratings) as meal_rating_rows;
