-- Run this once in the Supabase SQL editor before enabling the homepage form.
-- Each signed-in user can read and update only their own daily response.

create table if not exists public.meal_ratings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 80),
  rating_date date not null,
  breakfast_score smallint not null check (breakfast_score between 1 and 5),
  lunch_score smallint not null check (lunch_score between 1 and 5),
  dinner_score smallint not null check (dinner_score between 1 and 5),
  comment text check (comment is null or char_length(comment) <= 500),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, rating_date)
);

alter table public.meal_ratings enable row level security;

revoke all on table public.meal_ratings from anon;
grant select, insert, update on table public.meal_ratings to authenticated;
grant usage, select on sequence public.meal_ratings_id_seq to authenticated;

drop policy if exists "Users can read their own meal ratings" on public.meal_ratings;
create policy "Users can read their own meal ratings"
on public.meal_ratings for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert their own meal ratings" on public.meal_ratings;
create policy "Users can insert their own meal ratings"
on public.meal_ratings for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own meal ratings" on public.meal_ratings;
create policy "Users can update their own meal ratings"
on public.meal_ratings for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create or replace function public.set_meal_rating_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists meal_ratings_set_updated_at on public.meal_ratings;
create trigger meal_ratings_set_updated_at
before update on public.meal_ratings
for each row execute function public.set_meal_rating_updated_at();
