(function(){
  const escapeHtml=value=>{const node=document.createElement('div');node.textContent=value||'';return node.innerHTML};
  const relativeTime=value=>{const seconds=Math.max(1,Math.floor((Date.now()-new Date(value).getTime())/1000)),f=new Intl.RelativeTimeFormat('zh-CN',{numeric:'auto'});if(seconds<60)return f.format(-seconds,'second');const minutes=Math.floor(seconds/60);if(minutes<60)return f.format(-minutes,'minute');const hours=Math.floor(minutes/60);if(hours<24)return f.format(-hours,'hour');const days=Math.floor(hours/24);return days<30?f.format(-days,'day'):new Date(value).toLocaleDateString('zh-CN',{month:'short',day:'numeric'})};
  function initGreeting(){const node=document.getElementById('dayGreeting');if(!node)return;const hour=new Date().getHours(),part=hour<6?'夜深了':hour<11?'早上好':hour<14?'中午好':hour<18?'下午好':'晚上好';node.textContent=`${part} · 校园社区在线`}
  function initCarousel(){const slides=[...document.querySelectorAll('.hero-slide')],host=document.getElementById('heroDots');if(!slides.length||!host)return;let current=0,timer;const dots=slides.map((slide,index)=>{const button=document.createElement('button');button.type='button';button.className=`hero-dot${index===0?' active':''}`;button.setAttribute('aria-label',`显示第 ${index+1} 张：${slide.dataset.label}`);host.appendChild(button);return button});const show=(next,restart=false)=>{current=(next+slides.length)%slides.length;slides.forEach((slide,index)=>slide.classList.toggle('active',index===current));dots.forEach((dot,index)=>dot.classList.toggle('active',index===current));if(restart)schedule()};const schedule=()=>{clearInterval(timer);if(!matchMedia('(prefers-reduced-motion: reduce)').matches)timer=setInterval(()=>show(current+1),6000)};dots.forEach((dot,index)=>dot.addEventListener('click',()=>show(index,true)));document.getElementById('prevSlide')?.addEventListener('click',()=>show(current-1,true));document.getElementById('nextSlide')?.addEventListener('click',()=>show(current+1,true));document.querySelector('.hero')?.addEventListener('mouseenter',()=>clearInterval(timer));document.querySelector('.hero')?.addEventListener('mouseleave',schedule);document.addEventListener('visibilitychange',()=>document.hidden?clearInterval(timer):schedule());schedule()}
  async function loadFeed(){const host=document.getElementById('latestFeed');if(!host||!window.supabase)return;try{const client=window.supabase.createClient('https://bbcnrsktqarvceekrswb.supabase.co','eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJiYmNucnNrdHFhcnZjZWVrcnN3YiIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzc5NTI1MTg2LCJleHAiOjIwOTUxMDExODZ9.Mu6GW91z1HW2iX-tbQgH5qXrvpG2SPc9QoqCxGvV-54');const{data,error}=await client.from('messages').select('id,username,content,created_at').eq('flag',1).is('reply_to',null).order('created_at',{ascending:false}).limit(3);if(error)throw error;if(!data?.length){host.innerHTML='<div class="feed-card"><p class="feed-content">校墙还很安静，成为第一个分享校园故事的人吧。</p><a class="text-link" href="messages.html">发布第一条留言 →</a></div>';return}host.innerHTML=data.map(item=>`<article class="feed-card"><div class="feed-meta"><span class="feed-author"><span class="feed-avatar">${escapeHtml(item.username==='匿名用户'?'匿':item.username?.slice(0,1)||'I')}</span>${escapeHtml(item.username||'ISAer')}</span><time datetime="${escapeHtml(item.created_at)}">${relativeTime(item.created_at)}</time></div><p class="feed-content">${escapeHtml(item.content)}</p><a class="text-link" href="details.html?id=${encodeURIComponent(item.id)}">进入讨论 →</a></article>`).join('')}catch(error){host.innerHTML='<div class="feed-card"><p class="feed-content">暂时无法同步最新动态，你仍可以进入校墙查看或发布内容。</p><a class="text-link" href="messages.html">前往校墙 →</a></div>'}}
  async function loadNotices(){const host=document.getElementById('latestNotices');if(!host)return;try{const response=await fetch('./notice.html');if(!response.ok)throw new Error();const doc=new DOMParser().parseFromString(await response.text(),'text/html'),notices=[...doc.querySelectorAll('.notice-item')].slice(0,3);host.innerHTML=notices.map(item=>{const title=item.querySelector('h3')?.textContent.trim()||'站内公告',match=item.textContent.match(/20\d{2}年\d{1,2}月\d{1,2}日/);return`<a class="notice-row" href="notice.html"><span class="notice-date">${escapeHtml(match?.[0]||'最新')}</span><span class="notice-title">${escapeHtml(title)}</span><span aria-hidden="true">→</span></a>`}).join('')}catch(error){host.innerHTML='<a class="notice-row" href="notice.html"><span class="notice-date">最新</span><span class="notice-title">前往公告页查看更新</span><span>→</span></a>'}}
  document.addEventListener('DOMContentLoaded',()=>{initGreeting();initCarousel();loadNotices();loadFeed()});
})();
